name: Build Docker

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Construir imagem Docker
        run: docker build -t meu-site .

      - name: Listar imagens
        run: docker images
